# Generated by Django 4.2.17 on 2025-01-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
