# Generated by Django 4.2.17 on 2025-01-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0002_alter_campo_descricao_alter_campo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='data_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
