# Generated by Django 4.2.17 on 2025-01-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0003_campo_data_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='capacidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campo',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='preco_por_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campo',
            name='data_reserva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
