# Generated by Django 4.2.17 on 2025-01-06 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projetoapp', '0004_campo_capacidade_campo_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='iluminacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campo',
            name='tipo_gramado',
            field=models.CharField(choices=[('sintetico', 'Sintético'), ('natural', 'Natural')], default='sintetico', max_length=100),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
