# Generated by Django 4.2.17 on 2025-01-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0006_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='data_reserva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
