# Generated by Django 4.2.17 on 2025-01-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0007_alter_campo_data_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cidade',
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
    ]
