# Generated by Django 4.2.17 on 2025-01-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoapp', '0010_alter_campo_preco_por_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pagamento',
            field=models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'Pix')], default='credito', max_length=100),
        ),
    ]
